const mutationTypes = {
  // memo
  CHECK_MEMO: 'CHECK_MEMO',
  STAR_MEMO: 'STAR_MEMO',
  ADD_MEMO: 'ADD_MEMO',
  MODIFY_MEMO: 'MODIFY_MEMO',
  DELETE_MEMO: 'DELETE_MEMO',
  DROP_MEMO: 'DROP_MEMO',
  SYNC_MEMO: 'SYNC_MEMO',
  // switch
  SWITCH_DISPLAY: 'SWITCH_DISPLAY',
  SWITCH_BY_TIME: 'SWITCH_BY_TIME'
}

export default mutationTypes;
